
#General settings
[profiles]
	#A list of dimensions with associated city generation profiles (format <dimensionid>=<profilename>
	dimensionsWithProfiles = ["lostcities:lostcity=biosphere", "lostworlds:abyss=biosphere_caves", "mypack:lostcity=biosphere", "mypack:lostcity_wasteland_1=wasteland", "mypack:lostcity_ancient_1=ancient", "mypack:lostcity_atlantis_1=atlantis", "mypack:lostcity_bio_wasteland_1=bio_wasteland", "mypack:lostcity_biosphere_1=biosphere", "mypack:lostcity_biosphere_caves_1=biosphere_caves", "mypack:lostcity_cavern_1=cavern", "mypack:lostcity_default_1=default", "mypack:lostcity_floating_1=floating", "mypack:lostcity_largecities_1=largecities", "mypack:lostcity_nodamage_1=nodamage", "mypack:lostcity_onlycities_1=onlycities", "mypack:lostcity_rarecities_1=rarecities", "mypack:lostcity_safe_1=safe", "mypack:lostcity_space_1=space", "mypack:lostcity_tallbuildings_1=tallbuildings", "mypack:lostcity_void_outside_1=void_outside"]
	#If true then a different heightmap generation algorithm is used which should be slightly more efficient. Be careful with this as it might not be 100% compatible with some other terrain generation mods!
	optimizedHeightmap = false
	#The size of the chunk grid used for heightmap sampling. Default is 1 which means every chunk is sampled. Higher values will sample less chunks and thus be faster but also less accurate
	#Range: 1 ~ 100
	heightSampleSize = 3

